# Generated by Django 3.2.4 on 2021-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conferencia', '0003_auto_20210608_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('correo', models.EmailField(max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
